<?php snippet('header') ?>
  <main class="main" role="main">
 <h1><?php echo $page->title()->html() ?></h1>
    <!-- Start cssSlider.com -->
    <!-- Generated by cssSlider.com 2.1 -->
    <link rel="stylesheet" href="Slider_files/csss_engine1/style.css">
    <!--[if IE]><link rel="stylesheet" href="Slider_files/csss_engine1/ie.css"><![endif]-->
    <!--[if lte IE 9]><script type="text/javascript" src="Slider_files/csss_engine1/ie.js"></script><![endif]-->
     <div class="csslider1 autoplay ">
    <input name="cs_anchor1" id="cs_slide1_0" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_1" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_2" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_3" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_4" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_5" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_6" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_7" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_8" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_9" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_10" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_11" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_12" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_13" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_14" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_slide1_15" type="radio" class="cs_anchor slide">
    <input name="cs_anchor1" id="cs_play1" type="radio" class="cs_anchor" checked="">
    <input name="cs_anchor1" id="cs_pause1_0" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_1" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_2" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_3" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_4" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_5" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_6" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_7" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_8" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_9" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_10" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_11" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_12" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_13" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_14" type="radio" class="cs_anchor pause">
    <input name="cs_anchor1" id="cs_pause1_15" type="radio" class="cs_anchor pause">
    <ul>
      <li class="cs_skeleton"><img src="Slider_files/csss_images1/2015_casino.jpg" style="width: 100%;"></li>
      <li class="num0 img slide"> <img src="Slider_files/csss_images1/2015_casino.jpg" alt="Casino" title="Casino"></li>
      <li class="num1 img slide"> <img src="Slider_files/csss_images1/2015_dose.jpg" alt="Der Dose" title="Der Dose"></li>
      <li class="num2 img slide"> <img src="Slider_files/csss_images1/2015_duo.jpg" alt="2015_Duo" title="2015_Duo"></li>
      <li class="num3 img slide"> <img src="Slider_files/csss_images1/2015_hof.jpg" alt="2015_Hof" title="2015_Hof"></li>
      <li class="num4 img slide"> <img src="Slider_files/csss_images1/2015_hof2.jpg" alt="2015_Hof2" title="2015_Hof2"></li>
      <li class="num5 img slide"> <img src="Slider_files/csss_images1/2015_hof3.jpg" alt="2015_Hof3" title="2015_Hof3"></li>
      <li class="num6 img slide"> <img src="Slider_files/csss_images1/2015_luft.jpg" alt="2015_Luft" title="2015_Luft"></li>
      <li class="num7 img slide"> <img src="Slider_files/csss_images1/2015_orch.jpg" alt="2015_Orch" title="2015_Orch"></li>
      <li class="num8 img slide"> <img src="Slider_files/csss_images1/2015_prod.jpg" alt="2015_Prod" title="2015_Prod"></li>
      <li class="num9 img slide"> <img src="Slider_files/csss_images1/2015_prod2.jpg" alt="2015_Prod2" title="2015_Prod2"></li>
      <li class="num10 img slide"> <img src="Slider_files/csss_images1/2015_prod3.jpg" alt="2015_Prod3" title="2015_Prod3"></li>
      <li class="num11 img slide"> <img src="Slider_files/csss_images1/2015_rasga.jpg" alt="2015_Rasga" title="2015_Rasga"></li>
      <li class="num12 img slide"> <img src="Slider_files/csss_images1/2015_refugium.jpg" alt="2015_Refugium" title="2015_Refugium"></li>
      <li class="num13 img slide"> <img src="Slider_files/csss_images1/2015_sonic.jpg" alt="2015_Sonic" title="2015_Sonic"></li>
      <li class="num14 img slide"> <img src="Slider_files/csss_images1/2015_stra+.jpg" alt="2015_Stra+ƒ" title="2015_Stra+ƒ"></li>
      <li class="num15 img slide"> <img src="Slider_files/csss_images1/2015_stra.jpg" alt="2015_Straß" title="2015_Straß"></li>
    </ul><div class="cs_engine"><a href="http://cssslider.com">http://cssslider.com</a> by cssSlider.com v2.1m</div>
    
    
    <div class="cs_arrowprev">
      <label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
      <label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
      <label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
      <label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
      <label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
      <label class="num5" for="cs_slide1_5"><span><i></i><b></b></span></label>
      <label class="num6" for="cs_slide1_6"><span><i></i><b></b></span></label>
      <label class="num7" for="cs_slide1_7"><span><i></i><b></b></span></label>
      <label class="num8" for="cs_slide1_8"><span><i></i><b></b></span></label>
      <label class="num9" for="cs_slide1_9"><span><i></i><b></b></span></label>
      <label class="num10" for="cs_slide1_10"><span><i></i><b></b></span></label>
      <label class="num11" for="cs_slide1_11"><span><i></i><b></b></span></label>
      <label class="num12" for="cs_slide1_12"><span><i></i><b></b></span></label>
      <label class="num13" for="cs_slide1_13"><span><i></i><b></b></span></label>
      <label class="num14" for="cs_slide1_14"><span><i></i><b></b></span></label>
      <label class="num15" for="cs_slide1_15"><span><i></i><b></b></span></label>
    </div>
    <div class="cs_arrownext">
      <label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
      <label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
      <label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
      <label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
      <label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
      <label class="num5" for="cs_slide1_5"><span><i></i><b></b></span></label>
      <label class="num6" for="cs_slide1_6"><span><i></i><b></b></span></label>
      <label class="num7" for="cs_slide1_7"><span><i></i><b></b></span></label>
      <label class="num8" for="cs_slide1_8"><span><i></i><b></b></span></label>
      <label class="num9" for="cs_slide1_9"><span><i></i><b></b></span></label>
      <label class="num10" for="cs_slide1_10"><span><i></i><b></b></span></label>
      <label class="num11" for="cs_slide1_11"><span><i></i><b></b></span></label>
      <label class="num12" for="cs_slide1_12"><span><i></i><b></b></span></label>
      <label class="num13" for="cs_slide1_13"><span><i></i><b></b></span></label>
      <label class="num14" for="cs_slide1_14"><span><i></i><b></b></span></label>
      <label class="num15" for="cs_slide1_15"><span><i></i><b></b></span></label>
    </div>
    </div>
    <!-- End cssSlider.com -->
    <hr>
  </main>

<?php snippet('footer') ?>